### ISSUE TITLE
Crash when opening the Unseen Scribe gui

### ISSUE THREAD

**Issue by KIdWither** [Tuhljin/Automagy#10]
Note before opening the gui I placed a chest because a trapped chest was not showing up.
Any way hers the crash log.
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2/9/15 7:52 PM
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at net.minecraft.client.gui.inventory.GuiContainer.func_73876_c(GuiContainer.java:698)
	at tuhljin.automagy.gui.ModGuiContainer.func_73876_c(ModGuiContainer.java:98)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1649)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.gui.inventory.GuiContainer.func_73876_c(GuiContainer.java:698)
	at tuhljin.automagy.gui.ModGuiContainer.func_73876_c(ModGuiContainer.java:98)

-- Affected screen --
Details:
	Screen name: tuhljin.automagy.gui.GUIScribe

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['KidWither'/154, l='MpServer', x=-315.08, y=5.62, z=944.21]]
	Chunk stats: MultiplayerChunkCache: 272, 272
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-317,4,946), Chunk: (at 3,0,2 in -20,59; contains blocks -320,0,944 to -305,255,959), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 18619 game time, 18619 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 32 total; [EntityClientPlayerMP['KidWither'/154, l='MpServer', x=-315.08, y=5.62, z=944.21], EntityItem['item.item.egg'/884141, l='MpServer', x=-324.03, y=4.13, z=985.41], EntityHorse['Horse'/94, l='MpServer', x=-235.97, y=4.00, z=976.22], EntityItem['item.item.egg'/1132946, l='MpServer', x=-307.63, y=4.13, z=957.91], EntitySheep['Sheep'/34, l='MpServer', x=-390.97, y=4.00, z=945.91], EntitySheep['Sheep'/35, l='MpServer', x=-387.59, y=4.00, z=935.25], EntitySheep['Sheep'/33, l='MpServer', x=-390.22, y=4.00, z=948.38], EntityChicken['Chicken'/38, l='MpServer', x=-325.16, y=4.00, z=984.16], EntityChicken['Chicken'/39, l='MpServer', x=-323.56, y=4.00, z=987.41], EntityHorse['Horse'/96, l='MpServer', x=-238.88, y=4.00, z=979.75], EntityPig['Pig'/36, l='MpServer', x=-342.22, y=4.00, z=913.06], EntityPig['Pig'/37, l='MpServer', x=-336.16, y=4.00, z=987.94], EntitySheep['Sheep'/42, l='MpServer', x=-328.50, y=4.00, z=989.50], EntitySheep['Sheep'/43, l='MpServer', x=-326.94, y=4.00, z=982.84], EntityPig['Pig'/40, l='MpServer', x=-331.28, y=4.00, z=983.81], EntityPig['Pig'/41, l='MpServer', x=-326.75, y=4.00, z=989.84], EntitySheep['Sheep'/44, l='MpServer', x=-325.56, y=4.00, z=989.13], EntitySheep['Sheep'/45, l='MpServer', x=-329.41, y=4.00, z=982.50], EntitySheep['Sheep'/51, l='MpServer', x=-296.50, y=4.00, z=890.50], EntitySheep['Sheep'/50, l='MpServer', x=-287.75, y=4.00, z=891.22], EntitySheep['Sheep'/48, l='MpServer', x=-311.75, y=4.00, z=893.63], EntityPig['Pig'/55, l='MpServer', x=-289.28, y=4.00, z=891.69], EntityPig['Pig'/54, l='MpServer', x=-288.09, y=4.00, z=892.50], EntityPig['Pig'/53, l='MpServer', x=-289.19, y=4.00, z=895.47], EntitySheep['Sheep'/52, l='MpServer', x=-298.50, y=4.00, z=888.50], EntityPig['Pig'/59, l='MpServer', x=-299.88, y=4.00, z=894.78], EntityPig['Pig'/58, l='MpServer', x=-293.91, y=4.00, z=901.81], EntityPig['Pig'/57, l='MpServer', x=-299.13, y=4.00, z=905.94], EntityPig['Pig'/56, l='MpServer', x=-294.91, y=4.00, z=895.41], EntityItem['item.item.egg'/940478, l='MpServer', x=-324.97, y=4.13, z=982.94], EntityPig['Pig'/61, l='MpServer', x=-287.25, y=4.00, z=899.44], EntityChicken['Chicken'/60, l='MpServer', x=-305.59, y=4.00, z=958.56]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.2
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 224023296 bytes (213 MB) / 545202176 bytes (519 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 38 mods loaded, 38 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.3.4} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Automagy{0.19.1} [Automagy] (Automagy-1.7.10-0.19.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Botania{r1.4-158} [Botania] (Botania r1.4-158.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CarpentersBlocks{3.3.4.2} [Carpenter's Blocks] (Carpenters Blocks v3.3.4.2 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ChickenChunks{1.3.4.17} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.17-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FastCraft{1.19} [FastCraft] (fastcraft-1.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForbiddenMagic{1.7.10-0.552} [Forbidden Magic] (Forbidden Magic-1.7.10-0.552.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Bees{2.1.0} [Growthcraft Bees] (growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	JABBA{1.2.0a} [JABBA] (Jabba-1.2.0a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MapWriter{2.1.2} [MapWriter] (MapWriter-1.7.10-2.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cfm{3.4.7} [ß9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	harvestcraft{1.7.10d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-34.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TiCTooltips{1.2.0} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IguanaTweaksTConstruct{1.7.10-2.1.2.101} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-10.2.46, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Tuhljin** [comment]
I wasn't able to reproduce this. Trapped chests worked fine and putting a regular chest in front of the trapped chest didn't cause any issues either. Can you give me step by step instructions on how to reliably get it to crash? Does this happen if the only mods you have are Thaumcraft and Automagy?

Finally, if you do get it to crash again, there are two crash logs - server and client. The one you provided here isn't particularly informative. I'm guessing it's the client log. With "Ticking screen" issues like this, it's sometimes better to see the server log.

**Comment by KIdWither** [comment]
I seem to get the crash when, a node (i was testing how to set up an auto order system) and I remember placing the fallowing item in the chest ethereal essence. I have tested this in creative and got the crash however I have not tested it without any other mods. Also I do not know how to get the server crash log.

**Comment by Tuhljin** [comment]
I couldn't see any problem with ethereal essence being in a chest. The crash logs are found in the "crash-reports" folder. Where that is depends on how you've installed Minecraft (which launcher you're using, etc.), but "crash-reports" is generally found alongside the "mods" folder. Inside, it should be fairly obvious which are client and which are server logs because they have names like "crash-2014-12-18_17.24.33-server" (notice the "client" on the end there as well as the time stamp so you can find which one is the correct one).

**Comment by KIdWither** [comment]
I have decided to try and recreate the crash with the newest version however, it in stead kicks me from my game and sends me to the multiplayer screen. I have tried the newest version and it seems to be a problem with multiple essences of different types.

**Comment by KIdWither** [comment]
https://drive.google.com/open?id=0B1taqaUUp2IVeDU3XzZHdE01dUE&authuser=0 Here is the link to a video that should show you my set up seeing how it will not crash now (alone, will be putting the other mods in soon).

**Comment by Tuhljin** [comment]
If it's not crashing unless you have other mods in, then you need to use the process of elimination to determine which mod is causing the conflict.

**Comment by KIdWither** [comment]
Fast craft was the likely suspect but it did not help will report back in about a day with what mod does cause the crash.

**Comment by Tuhljin** [comment]
Thanks. It may be an issue that is best handled on my end, or an issue that you'll need the other mod author to handle, but either way, you'll likely need to provide the other crash log (labeled as server) if there is one.

**Comment by KIdWither** [comment]
Just found it I get the crash with nei installed I shall post the log there and sorry for wasting your time.

**Comment by Tuhljin** [comment]
No problem. I had NEI when I was doing my testing also, though, so you might have to do more digging around. Make sure that was the only mod you enabled and perhaps try different NEI settings. You might have another mod that adds extra tooltips to NEI or something and that's where the issue really is. It might still be something to look at on my end since Automagy integrates with NEI and actually runs that GUI differently depending on whether NEI is installed, but I would still need the server log to look into that.

**Comment by Tuhljin** [comment]
Also, make sure you have the latest NEI for 1.7.10.

**Comment by KIdWither** [comment]
My only predicament is that I can't seem to get a server crash log to be produced.

**Comment by KIdWither** [comment]
Neil and automagy are the only mods at the moment I have installed.

**Comment by KIdWither** [comment]
I am so sorry, it turns out that if you run minecraft in java 6 (not what my instance was using) it wants to crash. I am so sorry that I wasted your time, if you want my soul then take it.

**Comment by Tuhljin** [comment]
I'm glad you found out what the issue was. And thanks for letting me know about what you found. That will be helpful with other people reporting problems.
