### ISSUE TITLE
Vis Reader reading 0/0 nodes

### ISSUE THREAD

**Issue by Hazado** [Tuhljin/Automagy#11]
If a node has an aspect that gets completely bullied away, the vis reader still reads that aspect, so for any (low) auto it always reports 0.

**Comment by Hazado** [comment]
Posted this problem as well on Thaumcraft github issues
https://github.com/Azanor/thaumcraft/issues/1612

Figure this is probably a bug in thaumcraft anyways.

**Comment by Tuhljin** [comment]
This should be fixed in the next release.
