### ISSUE TITLE
Automagy 1.7.10 not showing up

### ISSUE THREAD

**Issue by cobaltSniper** [Tuhljin/Automagy#15]
I'm running Direwolf20 1.0.3 on ver 1.7.10, with all default mods plus Thaumic Horizons and Iguana tweaks, and Automagy enabled, but none of the mod items show up in NEI, and there's no tab for the research in the Thaumonomicon.
Is there something i'm missing, or is it just mod compatibility?

**Comment by Tuhljin** [comment]
I don't know of any reason it wouldn't work in that pack provided you've got the latest version of Thaumcraft installed. The only thing I could suggest would be double checking that you've got Automagy put in the right folder (maybe try adding/removing others mods to see if that's working). If that doesn't solve anything, then try the process of elimination to see if some combination of mods is resulting in a conflict.

**Comment by Tuhljin** [comment]
No reply so closing ticket. Reopen if necessary.
