### ISSUE TITLE
Inventorium not forming on server

### ISSUE THREAD

**Issue by Nocty201** [Tuhljin/Automagy#20]
We're running a modified and expanded FTB Infinity pack on a Cauldron server. Modlist here: http://www.technicpack.net/modpack/infinite-mayhem.616077/mods

I cannot get the inventorium to form. When I go to place the brain block (last, as per the book), nothing happens - it simply refuses to place. I've tried the exact same setup in single player creative mode, and it works fine. I can't see any blocks that would be interfering with the placement, and I'm reasonably certain that there's no "invisible blocks" in the area either.

Not sure how to help further, but if you'd like more information ask and I'll provide what I can.

Thanks for the awesome mod.

**Comment by Tuhljin** [comment]
You're sure you meet all the structural requirements? I've been able to form an Inventarium on my test server many times. Perhaps try setting it up in another place on the server. If it works there, then there's something wrong with the blocks around the other location.

**Comment by Nocty201** [comment]
You are correct - user error. My apologies.

Reformed it fine in the middle of a desert, so it's not your mod. Can't see why it didn't form in the original position; I moved it slightly and it formed happily. Can only suspect something didn't like it there, but lack tools to see why (am not an admin). 

Thanks again, I'll let you close this if you feel appropriate.
