### ISSUE TITLE
Requisition: Golem fails to pick up correctly

### ISSUE THREAD

**Issue by Ikabodo** [Tuhljin/Automagy#25]
Automagy version: 0.24.1
StorageDrawer version: 1.5.3

I'm posting this here, since it seems to be automagy. I've been trying to figure out what's been going on with my golem after trying to set up a requisition system. I receive no error-logs, so I'll try my best to describe to problem. I'm getting the feeling the golem "forgets" what he is supposed to do with the item he picks up some how... It's possible this is a user error, forgive me if it is.

One of these things happen:
1. The Golem fails to understand that it has already picked up an item. It goes to fetch it again, resulting in way to many pick-ups. 
2. The Golem picks up the item, but fails to put it in the right inventory. He drops it on the ground instead. 
3. The Golem goes to pick an item up, but doesn't pick it up at all. He returns to the base position and tries again. Over and over.

I've been trying to pinpoint when these things happen, but I'm having trouble. As far as I can tell, the golem simply fails to get the correct order from the pillar, or the inventory/slave from storage-drawers is sending the golem the wrong message somehow. It seems random, by I know there's a pattern to it.

Experiments so far:
- Tried asking the golem to collect from slave, controller and just simple drawers directly.
- Tried connecting the golem to several types of inventories, including item grate, hopper and chest.
- Tried different golems and upgrades, no difference
- Tried different distances between "drop-off" and "pick-up" (when it's very close, i.e. the pick up and the drop off is within one block of the golem, the golem just spaz out and start spurting the items all over the place)

Edit: I just realised there is a new version of storage-drawers. But reading the change-log did not mention anything about this issue. Never the less. I'll update and try again.

**Comment by Ikabodo** [comment]
Seems like the issue remains, with updated versions tested.

Is there any more testing or logs that I can help get?

**Comment by Tuhljin** [comment]
Does this only happen with storage drawers? Does it happen if Thaumcraft, Automagy, and Storage Drawers (and whatever they require) are the only mods installed?

**Comment by Ikabodo** [comment]
I'll set up a test-world with a minimum of mods as soon as possible!

**Comment by Ikabodo** [comment]
Real update:
Ok, i've been fiddling around with this for a while now.

* I wasn't able to replicate the issue on a server with fewer mods.
* I am able to replicate the issue, but only in my "original" base on the original server. 
* I was able to build a working inventarium on the original server, just a few hundred blocks away.

Could this be related to the area where the inventarium is built? The area is REALLY fps-laggy (not tps as far as I can tell), but I don't think that the lag has anything to do with automagy. But could the lag cause issues with the inventarium?

**Comment by Tuhljin** [comment]
FPS shouldn't have an effect. Are chunks perhaps getting unloaded, maybe loading and unloading?

If no golems are attached to the system, do you see any problems? E.g., if you place an order at the requisition tome, does the order stay there or does it disappear after a moment of simply waiting? If you close and re-open the GUI, are your orders still there until you clear them?

Do you have any problems with golems in that area, in general? Perhaps put some empty golems down to test that aren't linked to the Inventarium, tell them which items to pull out and then connect them to the drawer controller.

**Comment by Ikabodo** [comment]
I'll do some more testing with golems and the tome!

As far as I can remember about the ordering, the item stays in the requisition tomes list of things needing to be fetched. If there is a golem attached, he picks it up, but drops it on the way to the drop-of-point. He then returns to pick it up again, since it's still in the list. If there is no golem attached, the item just stays in the list. I'll have to see if it disappears after a while. 

I've not had any other problems with golems in the area that I know of. But I HAVE had a lot of problems with [disconnecting vis-relays](https://github.com/Azanor/thaumcraft/issues/1422). I figure this could indicate that the chunks are being loaded and reloaded, but I'm unsure how to test this. 

I'll see if I can record a video of the golem flipping out too.

**Comment by Tuhljin** [comment]
Was your Inventarium Core perhaps set up before the requisition system was added? Either way, could you try removing it and then placing it again (and then linking everything back to it, of course)?

If that doesn't help, then what I need is some way to reproduce the issue myself. Since it only seems to happen at that one place so far, there may be something unusual going on there. Chunk loaders, golem fetters/inhibitors in the area, number of golemic taskmasters, number of golems attached to the taskmasters, other golems in the area, and other such things should be considered. Heck, maybe there's something about those specific X,Y,Z map coordinates (though I doubt it).

I don't have a Patreon at the moment, no.

**Comment by einalex** [comment]
I have this same problem with mc vanilla chests as storage and the current version of automagy on this server:
http://www.minecraftforum.net/forums/servers/pc-servers/2471520-thaumcraft-4-2-3-5-server-new-add-ons

Stuff you mentioned to consider:
Chunk loaders: none
golem fetters/inhibitors: none
number of golemic taskmasters: two (but was also the case with only one)
number of golems attached to the taskmasters: one on each
other golems in the area: none

If you want to take a look at the problem directly, we could also meet on the server

**Comment by Tuhljin** [comment]
I need a way to duplicate this inside my development environment. If you can find a way to reliably reproduce it in test worlds, then let me know what you did to make that happen. I haven't been able to reproduce the problem so there has to be something different you're doing, something about the location you're in, and/or something about the other mods installed, etc.

**Comment by einalex** [comment]
@Ikabodo do you have running grief prevention on the system the error occurs?

**Comment by Ikabodo** [comment]
Old.
