### ISSUE TITLE
Unseen Scribes Only Recognizing Seemingly Random Containers

### ISSUE THREAD

**Issue by AranaiRa** [Tuhljin/Automagy#26]
On a multiplayer server, I have an Inventarium set up. I've got an Unseen Scribe set up pointing at a pile of Better Barrels, but it will only pay attention to seemingly random containers. All of the containers are within the 7x7x7 cube. For example, five of the barrels on the edge of the cube are noticed, but barrels in the middle except for one or two are ignored.

I've also tried this with containers, and using both the scrivener's occulus and just putting the container type next to the scribe. The same issue persists. I have not been able to replicate the issue in single player, but it persists in multiplayer.

**Comment by Tuhljin** [comment]
Do the items not show up consistently in the GUI or are you referring to problems extracting them using golems and the requisition system, as is discussed [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2125369-tc4-addon-automagy-v0-24-2-automation-and?comment=524)?

**Comment by AranaiRa** [comment]
I discovered the issue. In my single player instance I was using the silverwood bookcases, and on the server I'm using normal bookcases. It just doesn't have enough capacity as is, and swapping them out resolved the issue. Closing ticket.
