### ISSUE TITLE
Thirsty Tank doesn't distinguish between liquids when empty.

### ISSUE THREAD

**Issue by Xavion3** [Tuhljin/Automagy#27]
If you have a fluid next to the thirsty tank and then another fluid adjacent to that it will pump up the further away fluid as if it's the adjacent one even if it's not. See the picture for a better explanation, ignore the floodgate as that was testing if it could be automated but a quirk of them made it fail, the significant part is that upon flicking the lever the thirsty tank will suck up each block of water but generate a bucket of oil in itself, the conduit was made to extract it before another one could be pumped which meant it was empty and the bug would happen again. The end result is 9 buckets of oil in the drum from one bucket of oil and 8 buckets of water.
![Example](https://cloud.githubusercontent.com/assets/3487253/8197645/0d71f674-14de-11e5-926e-17067950f0ff.png)

**Comment by Tuhljin** [comment]
Thanks for the report. Your description made this easy to replicate.
