### ISSUE TITLE
Automagy fluidMilk from Thirsty Tanks

### ISSUE THREAD

**Issue by pyure** [Tuhljin/Automagy#29]
Thirsty Tank runes are freaking genius.  Unfortunately they seem to create a fluidMilk that isn't compatible with many milk recipes from other mods.

When I rightclick a bucket of vanilla milk on a vanilla tank, I get Milk.  But when I do the same with automagy milk I seem to get fluidMilk.  

I can bucket it out to unify it back to vanilla milk, but then mods such as ExtraUtilities and Gregtech don't handle them properly.

Is this anything you can address on your side or should I be harassing someone else?

Thanks Tuhljin

**Comment by Tuhljin** [comment]
I'm not sure what you mean by a "vanilla tank". There is no tank in vanilla Minecraft.

All fluid milk is added by one mod or another. If MFR is installed, then the thirsty tank will (if using default configs) produce MFR's milk. What mods are you using besides Automagy that add fluid milk?

**Comment by JasonMcRay** [comment]
What is happening is that liquid milk generated by Thirsty Tank (by milking cows with the Bovine glyph) can't be used in other mods recipes. We are unable to pump the milk directly to other machines (for example GregTech Fluid Canning Machine.

If i will fill any other tank with minecraft milk bucket and then will pump it into machine, it works.

Only mods adding Fluid Milk are: Automagy, Forestry and GregTech.

**Comment by JasonMcRay** [comment]
Here is a screenshot showing what exactly we mean. On the left is an OpenBlocks tank filled with milk which I got from milking cows manually.
On the right is a Thirsty Tank milking cows.

Left Milk goes into the machine in the middle without any issue. Right milk doesnt want to go in.
![2015-06-26_22 34 50](https://cloud.githubusercontent.com/assets/4236895/8386816/a149aff0-1c53-11e5-9df6-100eae29d818.png)

**Comment by pyure** [comment]
Tuhljin my apologies about the tank, I believe I meant to say BuildCraft tank. Hope it didn't cause too much confusion.

Jason McCray has done a better job of describing the issue.

**Comment by Tuhljin** [comment]
Closing this as the issue seems to have arisen due to previous versions of Automagy not supporting Forestry milk.

I'm not perfectly satisfied with the way it is handled, but it seems to be good enough for now. (IIRC, Forge added a better way to deal with "overlapping" fluids, e.g. multiple "milks", but it wasn't available in the version I developed for back when I first put in support for MFR milk.)

If there are still problems with the latest version, feel free to reopen or submit a new isse.
