### ISSUE TITLE
Runic Whitelist quantity mode overflows byte to yield a negative value

### ISSUE THREAD

**Issue by joakibj** [Tuhljin/Automagy#30]
Using shift + rightclick on an item in a Runic Whitelist allows to increase the quantity on an item up to 256. However, this is not supported by the byte datatype used, so it overflows to the negative range for any values above 127.

http://i.imgur.com/WQ6ElGL.png
http://i.imgur.com/7X69JcV.png

**Comment by Tuhljin** [comment]
This is an issue with Thaumcraft's ghost slots. I can't do much about it. I might implement my own solution in the future so I'll leave this issue open for now.

**Comment by Tuhljin** [comment]
For now, I'll see if I can at least get it to not go into the negatives like that.

**Comment by joakibj** [comment]
Not on a dedicated server instance
