### ISSUE TITLE
Alchemical Boiler Technomancy Compatibility

### ISSUE THREAD

**Issue by NullMagic** [Tuhljin/Automagy#32]
So the Alchemical Boiler is nice (Extremely so), but it doesn't accept the Galvanized Bellows from the Technomancy addon (http://minecraft.curseforge.com/mc-mods/229912-technomancy). The bellows basically work the same as regular bellows except that they accept RF and use it to break down items (in an Alchemical Furnace) as if they were being broken down with Alumentum. So while this isn't really an issue per say it'd be really nice to have cross mod compatibility allowing us to use the Galvanized Bellows on the Alchemical boiler.

**Comment by Tuhljin** [comment]
Please see https://github.com/theflogat/Technomancy/issues/126

**Comment by NullMagic** [comment]
Oh, awesome, thanks for the quick response!

**Comment by Tuhljin** [comment]
No problem. Just to be clear, I believe I've covered what I can on my side. The rest is on Technomancy's end.
