### ISSUE TITLE
Invalid mob spawning in the Nether

### ISSUE THREAD

**Issue by netzgeist** [Tuhljin/Automagy#36]
I apoligize if this is the wrong place or even not the authors bug. I debugged a full 4 hours before writing this report and I am not at a point where I dont assume its about configs.

Summary: Blazes and Wither Skelletons do spawn at any place in the nether. Light requirements still apply.
Additionals: Should be a crossmod interaction between MagicCookies and Automagy. 

http://i.imgur.com/CeSbuYq.jpg

Test scenario: 
1) Have both mods loaded, explore the nether. Blazes and Withers do spawn in groups between Zombie Pigmans and various other valid mobs.
2) Disable both mods, restart. /cofh killall and explore the nether again. No invalid mob spawning present.
3) Enable Automagy, restart. /cofh killall and explore the nether again. No invalid mob spawning present.
4) Disable Automagy, enable MagicCookies, restart. /cofh killall and explore the nether again. No invalid mob spawning present.
5) Enable Automagy(, leave MagicCookies enabled), restart. /cofh killall and explore the nether again. No invalid mob spawning present. (This gave me a headache!)
5) Restart. /cofh killall and explore the nether again. Invalid mob spawning present again.

Additional test scenario:
Each step was performed for ~10 minutes, pruning the spawns various times. Multiple map seeds were tested. 

Assembled modpack(Forge 1448):

19.07.2015  23:23           580.853 AgriCraft-1.7.10-1.3.1.jar
31.07.2015  18:32            90.094 AppleCore-mc1.7.10-1.1.0.jar
30.07.2015  10:43         2.624.397 AppleMilkTea2-1.7.10_2.8b.jar
19.07.2015  23:23           155.616 Aroma1997Core-1.7.10-1.0.2.14.jar
19.07.2015  23:23            16.872 AromaBackup-1.7.10-0.0.0.5.jar
29.07.2015  06:38         6.498.276 Automagy-1.7.10-0.26.3.jar
29.07.2015  06:39         5.266.476 BiblioCraft[v1.10.5][MC1.7.10].jar
30.07.2015  10:27           206.867 BiblioWoods[ExtraBiomesXL][v1.4].jar
30.07.2015  10:25           241.857 BiblioWoods[Natura][v1.5].jar
19.07.2015  23:10           868.472 BloodArsenal-1.7.10-1.1-14.jar
22.07.2015  16:02         9.457.610 BloodMagic-1.7.10-1.3.3-11.jar
29.07.2015  06:39        14.944.040 Botania r1.7-208.jar
19.07.2015  23:26           494.604 Carpenter's Blocks v3.3.6 - MC 1.7.10.jar
29.07.2015  06:56           106.701 ChickenChunks-1.7.10-1.3.4.19-universal.jar
19.07.2015  23:08         5.896.144 Chisel2-2.4.1.40.jar
19.07.2015  23:08             5.494 ChiselTones-1.7.10-1.0-1.jar
30.07.2015  11:42         1.502.264 clockworkphase-1.7.10_1.0f.jar
29.07.2015  06:56           158.865 CodeChickenCore-1.7.10-1.0.6.43-universal.jar
19.07.2015  23:45         1.068.485 CoFHCore-[1.7.10]3.0.3-303.jar
19.07.2015  23:45           282.208 CoFHLib-[1.7.10]1.0.3-175.jar
30.07.2015  10:53            60.890 CookieCore-1.7.10-1.4.0-11.jar
29.07.2015  08:05           109.173 CustomMainMenu-MC1.7.10-1.6.jar
19.07.2015  23:26            60.626 denseores-1.6.2.jar
19.07.2015  23:44           106.884 DummyCore1.13.jar
29.07.2015  06:39           442.661 EnderCore-1.7.10-0.0.1.13_alpha.jar
29.07.2015  06:55           144.584 EnderStorage-1.7.10-1.4.7.33-universal.jar
19.07.2015  23:22        11.785.875 EssentialCraftv4.5.1710.223.jar
19.07.2015  23:34           882.899 extrabiomesxl_1.7.10-3.16.2.jar
30.07.2015  10:12        11.151.826 ExtraTiC-1.7.10-1.4.5.jar
29.07.2015  06:39         2.092.549 extrautilities-1.2.9.jar
25.06.2015  10:35           116.959 fastcraft-1.21.jar
30.07.2015  11:42         6.060.363 Flaxbeard'sSteamPower-1.7.10-0.28.7.jar
19.07.2015  23:07           609.807 Forbidden Magic-1.7.10-0.57.jar
25.07.2015  07:55           943.474 ForgeMultipart-1.7.10-1.2.0.345-universal.jar
19.07.2015  23:25           184.951 Guide-API-1.7.10-1.0.1-20.jar
24.07.2015  07:24            47.065 hopperductmod-1.7.10-1.3.2.jar
20.07.2015  06:45           126.448 INpureCore-[1.7.10]1.0.0B9-62.jar
19.07.2015  23:23           224.461 InventoryTweaks-1.59-dev-152.jar
30.07.2015  10:13           158.100 ironchest-1.7.10-6.0.60.741-universal.jar
30.07.2015  10:42           360.144 IvToolkit-1.2.jar
19.07.2015  23:23           440.712 Jabba-1.2.1a_1.7.10.jar
20.07.2015  02:48         1.542.602 journeymap-1.7.10-5.1.0-unlimited.jar
19.07.2015  23:22         3.966.675 MagicCookies-1.0.6.7.jar
19.07.2015  23:23           196.807 Mantle-1.7.10-0.3.2.jar
19.07.2015  23:24           963.268 MineTweaker3-1.7.10-3.0.9C.jar
24.07.2015  07:24            45.689 ModelCitizens-mc1.7.10-1.0.1.jar
24.07.2015  07:51           527.831 ModTweaker~2-0.9.1.jar
24.07.2015  07:51            17.583 Morpheus-1.7.10-1.6.9.jar
19.07.2015  23:23           891.845 natura-1.7.10-2.2.0.1.jar
24.07.2015  07:51           103.492 neiaddons-1.12.11.36-mc1.7.10.jar
19.07.2015  23:23           176.021 NEIIntegration-MC1.7.10-1.0.11.jar
19.07.2015  23:23            79.555 NetherOres-[1.7.10]2.3.0-12.jar
19.07.2015  23:18            22.172 NodalMechanics-1.7-1.0-7.jar
29.07.2015  06:57           512.898 NotEnoughItems-1.7.10-1.0.4.107-universal.jar
22.07.2015  22:37         2.598.576 OpenBlocks-1.7.10-1.4.3.jar
22.07.2015  22:37           813.211 OpenModsLib-1.7.10-0.7.3.jar
19.07.2015  23:25         3.659.711 Railcraft_1.7.10-9.6.1.0.jar
30.07.2015  10:56            11.820 ResourceLoader-1.2.jar
19.07.2015  23:25         1.486.064 Sanguimancy-1.7.10-1.1.9-31.jar
19.07.2015  23:08           172.075 Sanguine Utilities-1.3.2.jar
30.07.2015  10:12           228.001 StevesWorkshop-0.5.1.jar
19.07.2015  23:24           428.719 StorageDrawers-1.7.10-1.5.12.jar
30.07.2015  10:16           102.726 StorageDrawers-Natura-1.7.10-1.0.2.jar
24.07.2015  06:39            89.875 supercraftingframe-1.7.10.3.jar
19.07.2015  23:11         2.653.000 TaintedMagic-1.1.5.4.jar
19.07.2015  23:18           116.878 tcnodetracker-1.7.10-1.1.2.jar
30.07.2015  10:01         5.492.700 TConstruct-1.7.10-1.8.5.jar
25.06.2015  10:36        12.565.807 Thaumcraft-1.7.10-4.2.3.5.jar
30.07.2015  10:11            68.794 thaumcraftneiplugin-1.7.10-1.7a.jar
31.07.2015  18:33         1.733.078 ThaumicBases-1.2.1710.16.jar
20.07.2015  02:18         1.982.603 ThaumicExploration-1.7.10-1.1-53.jar
19.07.2015  23:18         2.274.316 thaumichorizons-1.7.10-1.1.6.jar
29.07.2015  09:30         2.151.783 ThaumicTinkerer-2.5-1.7.10-507.jar
31.07.2015  18:32            52.002 TiCTooltips-mc1.7.10-1.2.5.jar
30.07.2015  10:14           218.626 TMechworks-1.7.10-0.2.14.100.jar
19.07.2015  23:07           301.703 TravellersGear-1.7.10-1.16.4.jar
19.07.2015  23:26         3.682.125 twilightforest-1.7.10-2.3.7.jar
19.07.2015  23:08           544.821 Waila-1.5.10_1.7.10.jar
19.07.2015  23:23            25.539 WailaHarvestability-mc1.7.x-1.1.2.jar
19.07.2015  23:08            64.755 WAILAPlugins-MC1.7.10-0.1.0-16.jar
19.07.2015  23:08            69.854 Wawla-1.3.1-1.7.10.jar
19.07.2015  23:26         7.009.956 witchery-1.7.10-0.24.1.jar
19.07.2015  23:07         4.186.414 WitchingGadgets-1.7.10-1.1.9.jar
19.07.2015  23:08           556.982 Ztones-1.7.10-2.2.1.jar

**Comment by Tuhljin** [comment]
Automagy doesn't change any spawn rules. The only interaction it does with spawning is convert certain vanilla spawns into endermen when you've got a shattered avarice pearl on you and the biome is a valid place for endermen. I don't know how this could be related to Automagy. Perhaps it has something to do with mod loading order? What does the author of Magic Cookies say?

**Comment by netzgeist** [comment]
Nothing yet. As I was unable to locate his GitHub repo, I have crossposted this report to his curseforge page. He seems to be very active there:


http://minecraft.curseforge.com/mc-mods/231755-magic-cookies?comment=13

**Comment by netzgeist** [comment]
You may want to close this. Spending some more time on the bug, I can now definately say, Magic Cookies is the offendor. I am sure its a crossmod problem, but unlikely your fault.
