### ISSUE TITLE
Crash while loading a world

### ISSUE THREAD

**Issue by Querdenker9** [Tuhljin/Automagy#37]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 8/3/15 11:19 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: -98
	at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429)
	at tuhljin.automagy.lib.ProxyClient.getKeyName(ProxyClient.java:326)
	at tuhljin.automagy.lib.AutomagyKeyHandler.getKeyName(AutomagyKeyHandler.java:34)
	at tuhljin.automagy.config.ModResearchItems.makeClientAdjustments(ModResearchItems.java:490)
	at tuhljin.automagy.lib.events.ClientEventHandler.onTick(ClientEventHandler.java:32)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_293_ClientEventHandler_onTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:276)
	at org.multimc.onesix.OneSixLauncher$1.run(OneSixLauncher.java:351)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429)
	at tuhljin.automagy.lib.ProxyClient.getKeyName(ProxyClient.java:326)
	at tuhljin.automagy.lib.AutomagyKeyHandler.getKeyName(AutomagyKeyHandler.java:34)
	at tuhljin.automagy.config.ModResearchItems.makeClientAdjustments(ModResearchItems.java:490)
	at tuhljin.automagy.lib.events.ClientEventHandler.onTick(ClientEventHandler.java:32)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_293_ClientEventHandler_onTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Querdenker_9'/204, l='MpServer', x=286.50, y=40.62, z=-161.50]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (283,64,-169), Chunk: (at 11,4,7 in 17,-11; contains blocks 272,0,-176 to 287,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 59 game time, 59 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 103 total; [EntitySkeleton['Skeleton'/520, l='MpServer', x=324.50, y=35.00, z=-210.50], EntitySkeleton['Skeleton'/521, l='MpServer', x=324.50, y=35.00, z=-213.50], EntityBat['Bat'/528, l='MpServer', x=305.50, y=21.00, z=-149.50], EntitySquid['Squid'/797, l='MpServer', x=268.50, y=61.00, z=-127.50], EntitySquid['Squid'/551, l='MpServer', x=270.50, y=61.00, z=-130.50], EntitySquid['Squid'/552, l='MpServer', x=273.50, y=61.00, z=-129.50], EntitySlime['Slime'/814, l='MpServer', x=208.50, y=11.00, z=-139.50], EntityItem['item.tile.mushroom8'/49, l='MpServer', x=238.06, y=11.13, z=-181.16], EntityBat['Bat'/566, l='MpServer', x=337.50, y=21.00, z=-146.50], EntityCreeper['Creeper'/831, l='MpServer', x=217.50, y=46.00, z=-106.50], EntityItem['item.tile.mushroom9'/68, l='MpServer', x=342.75, y=11.13, z=-200.25], EntityItem['item.tile.mushroom7'/70, l='MpServer', x=257.38, y=15.13, z=-183.91], EntityItem['item.tile.mushroom0'/79, l='MpServer', x=307.94, y=21.13, z=-153.44], EntityBat['Bat'/849, l='MpServer', x=207.50, y=15.00, z=-121.50], EntityBat['Bat'/595, l='MpServer', x=319.50, y=22.00, z=-206.50], EntitySkeleton['Skeleton'/854, l='MpServer', x=269.50, y=33.00, z=-144.50], EntityItem['item.tile.mushroom6'/87, l='MpServer', x=324.19, y=27.13, z=-118.19], EntityItem['item.tile.flowers2.minersdelight'/88, l='MpServer', x=324.19, y=27.13, z=-118.16], EntityItem['item.tile.flowers2.minersdelight'/95, l='MpServer', x=328.66, y=24.13, z=-119.16], EntityItem['item.tile.flowers2.minersdelight'/96, l='MpServer', x=330.63, y=22.13, z=-123.56], EntityItem['item.tile.flowers2.minersdelight'/97, l='MpServer', x=333.44, y=21.13, z=-126.81], EntityItem['item.tile.flowers2.minersdelight'/98, l='MpServer', x=331.31, y=22.13, z=-125.38], EntityItem['item.tile.flowers2.minersdelight'/99, l='MpServer', x=330.06, y=27.13, z=-120.19], EntitySkeleton['Skeleton'/1123, l='MpServer', x=263.50, y=33.00, z=-149.50], EntityFallingBlock['Falling Block'/1130, l='MpServer', x=168.50, y=36.50, z=-266.50], EntityFallingBlock['Falling Block'/1131, l='MpServer', x=154.50, y=41.44, z=-269.50], EntityBat['Bat'/620, l='MpServer', x=363.88, y=22.66, z=-229.16], EntityFallingBlock['Falling Block'/1132, l='MpServer', x=155.50, y=41.44, z=-268.50], EntityFallingBlock['Falling Block'/1133, l='MpServer', x=155.50, y=41.44, z=-267.50], EntityFallingBlock['Falling Block'/1134, l='MpServer', x=154.50, y=42.44, z=-268.50], EntityFallingBlock['Falling Block'/1135, l='MpServer', x=154.50, y=42.44, z=-267.50], EntityFallingBlock['Falling Block'/1136, l='MpServer', x=153.50, y=42.44, z=-268.50], EntityFallingBlock['Falling Block'/1137, l='MpServer', x=153.50, y=42.44, z=-267.50], EntityFallingBlock['Falling Block'/1138, l='MpServer', x=152.50, y=41.44, z=-268.50], EntityFallingBlock['Falling Block'/1139, l='MpServer', x=152.50, y=41.44, z=-267.50], EntityFallingBlock['Falling Block'/1140, l='MpServer', x=152.50, y=41.44, z=-269.50], EntityFallingBlock['Falling Block'/1141, l='MpServer', x=152.50, y=41.44, z=-266.50], EntityFallingBlock['Falling Block'/1142, l='MpServer', x=153.50, y=42.44, z=-269.50], EntityFallingBlock['Falling Block'/1143, l='MpServer', x=153.50, y=42.44, z=-266.50], EntityFallingBlock['Falling Block'/1144, l='MpServer', x=154.50, y=42.44, z=-266.50], EntityFallingBlock['Falling Block'/1145, l='MpServer', x=155.50, y=41.44, z=-266.50], EntityFallingBlock['Falling Block'/1154, l='MpServer', x=146.50, y=64.50, z=-263.50], EntityFallingBlock['Falling Block'/1156, l='MpServer', x=146.50, y=42.50, z=-222.50], EntityFallingBlock['Falling Block'/1157, l='MpServer', x=146.50, y=42.50, z=-221.50], EntityFallingBlock['Falling Block'/1158, l='MpServer', x=145.50, y=42.50, z=-222.50], EntityFallingBlock['Falling Block'/1159, l='MpServer', x=145.50, y=42.50, z=-221.50], EntityFallingBlock['Falling Block'/1160, l='MpServer', x=144.50, y=41.50, z=-223.50], EntityFallingBlock['Falling Block'/1161, l='MpServer', x=144.50, y=41.50, z=-222.50], EntityFallingBlock['Falling Block'/1162, l='MpServer', x=144.50, y=42.50, z=-221.50], EntityFallingBlock['Falling Block'/1163, l='MpServer', x=145.50, y=41.50, z=-223.50], EntityFallingBlock['Falling Block'/1165, l='MpServer', x=144.50, y=41.50, z=-224.50], EntityFallingBlock['Falling Block'/1166, l='MpServer', x=145.50, y=41.50, z=-224.50], EntityFallingBlock['Falling Block'/1194, l='MpServer', x=154.50, y=38.50, z=-235.50], EntityFallingBlock['Falling Block'/1195, l='MpServer', x=154.50, y=38.50, z=-234.50], EntityFallingBlock['Falling Block'/1196, l='MpServer', x=155.50, y=39.50, z=-235.50], EntityFallingBlock['Falling Block'/1197, l='MpServer', x=153.50, y=38.50, z=-235.50], EntityFallingBlock['Falling Block'/1198, l='MpServer', x=153.50, y=38.50, z=-234.50], EntityFallingBlock['Falling Block'/1199, l='MpServer', x=154.50, y=38.50, z=-236.50], EntityFallingBlock['Falling Block'/1200, l='MpServer', x=153.50, y=38.50, z=-233.50], EntityFallingBlock['Falling Block'/1201, l='MpServer', x=152.50, y=37.50, z=-232.50], EntityCreeper['Creeper'/436, l='MpServer', x=341.50, y=45.00, z=-138.50], EntitySkeleton['Skeleton'/1205, l='MpServer', x=303.50, y=42.00, z=-238.50], EntityZombie['Zombie'/438, l='MpServer', x=344.50, y=45.00, z=-131.50], EntitySkeleton['Skeleton'/1206, l='MpServer', x=305.50, y=42.00, z=-239.50], EntityZombie['Zombie'/1207, l='MpServer', x=303.50, y=42.00, z=-240.50], EntityFallingBlock['Falling Block'/1212, l='MpServer', x=150.50, y=59.50, z=-158.50], EntityFallingBlock['Falling Block'/1213, l='MpServer', x=149.50, y=60.50, z=-158.50], EntityZombie['Zombie'/958, l='MpServer', x=207.50, y=18.00, z=-106.50], EntityFallingBlock['Falling Block'/1214, l='MpServer', x=149.50, y=60.50, z=-157.50], EntityFallingBlock['Falling Block'/1215, l='MpServer', x=150.50, y=59.50, z=-159.50], EntityFallingBlock['Falling Block'/1216, l='MpServer', x=149.50, y=60.50, z=-159.50], EntityFallingBlock['Falling Block'/1217, l='MpServer', x=151.50, y=60.50, z=-159.50], EntityFallingBlock['Falling Block'/1218, l='MpServer', x=148.50, y=60.50, z=-159.50], EntityFallingBlock['Falling Block'/1219, l='MpServer', x=148.50, y=60.50, z=-158.50], EntityFallingBlock['Falling Block'/1220, l='MpServer', x=151.50, y=60.50, z=-160.50], EntityFallingBlock['Falling Block'/1221, l='MpServer', x=151.50, y=60.50, z=-161.50], EntityZombie['Zombie'/719, l='MpServer', x=363.50, y=20.00, z=-232.50], EntityCreeper['Creeper'/468, l='MpServer', x=357.50, y=18.00, z=-103.50], EntityClientPlayerMP['Querdenker_9'/204, l='MpServer', x=286.50, y=40.62, z=-161.50], EntitySkeleton['Skeleton'/216, l='MpServer', x=210.50, y=15.00, z=-121.50], EntityCreeper['Creeper'/987, l='MpServer', x=240.50, y=37.00, z=-184.50], EntityFallingBlock['Falling Block'/1252, l='MpServer', x=146.50, y=44.50, z=-101.50], EntityFallingBlock['Falling Block'/1253, l='MpServer', x=145.50, y=45.50, z=-100.50], EntityBat['Bat'/491, l='MpServer', x=354.44, y=46.03, z=-92.56], EntityFallingBlock['Falling Block'/1262, l='MpServer', x=147.50, y=63.50, z=-118.50], EntityFallingBlock['Falling Block'/1263, l='MpServer', x=148.50, y=63.50, z=-118.50], EntityFallingBlock['Falling Block'/1264, l='MpServer', x=146.50, y=63.50, z=-118.50], EntityFallingBlock['Falling Block'/1265, l='MpServer', x=147.50, y=63.50, z=-119.50], EntityFallingBlock['Falling Block'/1266, l='MpServer', x=146.50, y=62.50, z=-117.50], EntityFallingBlock['Falling Block'/1267, l='MpServer', x=146.50, y=63.50, z=-119.50], EntityFallingBlock['Falling Block'/1268, l='MpServer', x=145.50, y=62.50, z=-119.50], EntityFallingBlock['Falling Block'/1269, l='MpServer', x=145.50, y=62.50, z=-118.50], EntityFallingBlock['Falling Block'/1270, l='MpServer', x=145.50, y=62.50, z=-120.50], EntityFallingBlock['Falling Block'/1271, l='MpServer', x=144.50, y=62.50, z=-120.50], EntityFallingBlock['Falling Block'/1272, l='MpServer', x=146.50, y=62.50, z=-106.50], EntityFallingBlock['Falling Block'/1273, l='MpServer', x=146.50, y=62.50, z=-105.50], EntityFallingBlock['Falling Block'/1274, l='MpServer', x=146.50, y=62.50, z=-104.50], EntityFallingBlock['Falling Block'/1275, l='MpServer', x=146.50, y=62.50, z=-103.50], EntityFallingBlock['Falling Block'/1276, l='MpServer', x=147.50, y=61.50, z=-101.50], EntitySquid['Squid'/1021, l='MpServer', x=276.50, y=62.00, z=-134.50], EntityFallingBlock['Falling Block'/1277, l='MpServer', x=147.50, y=61.50, z=-100.50], EntityCreeper['Creeper'/254, l='MpServer', x=303.50, y=22.00, z=-147.50], EntitySkeleton['Skeleton'/1023, l='MpServer', x=226.50, y=24.00, z=-180.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:276)
	at org.multimc.onesix.OneSixLauncher$1.run(OneSixLauncher.java:351)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1455322408 bytes (1387 MB) / 2772434944 bytes (2644 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAA	VeinMiner_coremod{0.27.1_build.unknown} [Core mod] (minecraft.jar) 
	UCHIJAAAA	WitchingGadgetsCore{1.1.9} [Witching Gadgets Core] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	bdlib{1.9.1.97} [BD Lib] (bdlib-1.9.1.97-mc1.7.10.jar) 
	UCHIJAAAA	ae2stuff{0.4.3.47} [AE2 Stuff] (ae2stuff-0.4.3.47-mc1.7.10.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	Automagy{0.26.3} [Automagy] (Automagy-1.7.10-0.26.3.jar) 
	UCHIJAAAA	BiblioCraft{1.10.5} [BiblioCraft] (BiblioCraft[v1.10.5][MC1.7.10].jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1364-universal.jar) 
	UCHIJAAAA	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UCHIJAAAA	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UCHIJAAAA	Botania{r1.7-208} [Botania] (Botania r1.7-208.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.4.1.40} [Chisel 2] (Chisel2-2.4.1.40.jar) 
	UCHIJAAAA	ctmlib{1.0.1.5} [CTMLib] (Chisel2-2.4.1.40.jar) 
	UCHIJAAAA	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) 
	UCHIJAAAA	props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar) 
	UCHIJAAAA	Ding{MC1.7.10} [Ding] (Ding-MC1.7.10.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal.jar) 
	UCHIJAAAA	extracells{2.2.73} [Extra Cells 2] (ExtraCells-1.7.10-2.2.73b129.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	fastleafdecay{1.1} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.1.jar) 
	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-507.jar) 
	UCHIJAAAA	ForbiddenMagic{1.7.10-0.57} [Forbidden Magic] (Forbidden Magic-1.7.10-0.57.jar) 
	UCHIJAAAA	GraveStone{2.12.3} [GraveStone] (GraveStone-2.12.4.jar) 
	UCHIJAAAA	infiniteinvo{1.0.41} [InfiniteInvo] (InfiniteInvo-1.0.41.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCHIJAAAA	journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar) 
	UCHIJAAAA	Magistics{8.0.0} [�o�bMagistics] (Magistics-1.7.10-0.7.6.jar) 
	UCHIJAAAA	NodalMechanics{1.7.10R1.0} [NodalMechanics] (NodalMechanics-1.7-1.0-7.jar) 
	UCHIJAAAA	neresources{0.1.0.106} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.106.jar) 
	UCHIJAAAA	particlelib{1} [Particle Library] (ParticleLib - 1.jar) 
	UCHIJAAAA	recallstones{0.5.2} [Recall Stones] (RecallStones-1.7.10-0.5.2.jar) 
	UCHIJAAAA	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.5.12} [Storage Drawers] (StorageDrawers-1.7.10-1.5.12.jar) 
	UCHIJAAAA	StorageDrawersBop{1.7.10-1.0.1} [Storage Drawers: Biomes O' Plenty Pack] (StorageDrawers-BiomesOPlenty-1.7.10-1.0.1.jar) 
	UCHIJAAAA	StorageDrawersNatura{1.7.10-1.0.2} [Storage Drawers: Natura Pack] (StorageDrawers-Natura-1.7.10-1.0.2.jar) 
	UCHIJAAAA	TaintedMagic{1.1.5.4} [Tainted Magic] (TaintedMagic-1.1.5.4.jar) 
	UCHIJAAAA	Talismans 2{1.1.6} [Talismans 2] (Talismans2-1.7.10-1.1.6.jar) 
	UCHIJAAAA	tcnodetracker{1.1.2} [TC Node Tracker] (tcnodetracker-1.7.10-1.1.2.jar) 
	UCHIJAAAA	benway_knowledge{0.1.1} [Thaumaturgical Knowledge] (Thaumaturgical Knowledge-0.1.1.jar) 
	UCHIJAAAA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJAAAA	thaumicadditions{0.019} [Thaumic Additions] (Thaumic Additions - 0.019.jar) 
	UCHIJAAAA	TU{1.0} [Thaumic Upholstry] (Thaumic_Upholstery-1.2_1.7.10.jar) 
	UCHIJAAAA	thaumicenergistics{0.8.10.10} [Thaumic Energistics] (thaumicenergistics-0.8.10.10.jar) 
	UCHIJAAAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJAAAA	ThaumicHorizons{1.1.5} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.6.jar) 
	UCHIJAAAA	thaumicinfusion{4.18} [Thaumic Infusion] (ThaumicInfusion-4.18.jar) 
	UCHIJAAAA	Translocator{1.1.2.15} [Translocator] (Translocator-1.7.10-1.1.2.15-universal.jar) 
	UCHIJAAAA	TravellersGear{1.16.4} [Traveller's Gear] (TravellersGear-1.7.10-1.16.4.jar) 
	UCHIJAAAA	TWarden{1.1.1} [Thaumic Warden] (TWarden-1.1.1.jar) 
	UCHIJAAAA	VeinMiner{0.27.1_build.unknown} [Vein Miner] (VeinMiner-1.7.10_0.27.1.unknown.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.27.1_build.unknown} [Mod Support] (VeinMiner-1.7.10_0.27.1.unknown.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCHIJAAAA	WarpTheory{1.7.10R1.0} [WarpTheory] (WarpTheory-1.7-1.0-24.jar) 
	UCHIJAAAA	wawla{1.3.1} [What Are We Looking At] (Wawla-1.3.1-1.7.10.jar) 
	UCHIJAAAA	WitchingGadgets{1.1.9} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.9.jar) 
	UCHIJAAAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1002' Renderer: 'AMD Radeon R7 M260'
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Mantle Environment: Environment healthy.
	List of loaded APIs: 
		* appliedenergistics2|API (rv2) from ThaumicTinkerer-2.5-1.7.10-507.jar
		* Baubles|API (1.0.1.10) from GraveStone-2.12.4.jar
		* BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.10-2.1.0.1364-universal.jar
		* BotaniaAPI (58) from Botania r1.7-208.jar
		* ChiselAPI (0.1.0) from Chisel2-2.4.1.40.jar
		* ChiselAPI|Carving (0.1.0) from Chisel2-2.4.1.40.jar
		* ChiselAPI|Rendering (0.1.0) from Chisel2-2.4.1.40.jar
		* CoFHAPI (1.7.10R1.0.2) from Thaumic Additions - 0.019.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from Thaumic Additions - 0.019.jar
		* ComputerCraft|API (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|FileSystem (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Lua (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Media (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Peripheral (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Redstone (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Turtle (1.73) from ComputerCraft1.73.jar
		* CSLib|API (1.0) from Decocraft-2.0.2_1.7.10.jar
		* ForestryAPI|apiculture (2.6.0) from GraveStone-2.12.4.jar
		* ForestryAPI|arboriculture (2.3.0) from GraveStone-2.12.4.jar
		* ForestryAPI|circuits (1.1.0) from GraveStone-2.12.4.jar
		* ForestryAPI|core (2.6.1) from GraveStone-2.12.4.jar
		* ForestryAPI|farming (1.1.0) from GraveStone-2.12.4.jar
		* ForestryAPI|food (1.1.0) from GraveStone-2.12.4.jar
		* ForestryAPI|fuels (2.0.1) from GraveStone-2.12.4.jar
		* ForestryAPI|genetics (2.7.0) from GraveStone-2.12.4.jar
		* ForestryAPI|hives (4.0.0) from GraveStone-2.12.4.jar
		* ForestryAPI|lepidopterology (1.1) from GraveStone-2.12.4.jar
		* ForestryAPI|mail (3.0.0) from GraveStone-2.12.4.jar
		* ForestryAPI|recipes (2.1.0) from GraveStone-2.12.4.jar
		* ForestryAPI|storage (2.3.0) from GraveStone-2.12.4.jar
		* ForestryAPI|world (1.1.0) from GraveStone-2.12.4.jar
		* IC2API (1.0) from Thaumic Additions - 0.019.jar
		* neresources|API (1.0) from NotEnoughResources-1.7.10-0.1.0.106.jar
		* STAPI (1.7.10-1.3) from Thaumic Additions - 0.019.jar
		* STAPI|power (1.7.10-1.3) from Thaumic Additions - 0.019.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* Thaumcraft|API (4.2.2.0) from Thaumic_Upholstery-1.2_1.7.10.jar
		* TravellersGear|API (1.0) from TravellersGear-1.7.10-1.16.4.jar
		* VeinMinerApi (0.1) from VeinMiner-1.7.10_0.27.1.unknown.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: AMD Radeon R7 M260 GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1002, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Tuhljin** [comment]
What key did you bind the crafting focus to?

**Comment by Querdenker9** [comment]
The Middle Button

**Comment by Tuhljin** [comment]
I believe I've fixed this for the next release. If you still have problems afterward, let me know.
