### ISSUE TITLE
Thaumostatic Spire does not work at all in 0.28.1

### ISSUE THREAD

**Issue by esidav** [Tuhljin/Automagy#44]
as mentioned in subject, Thaumostatic Spire does not work.
I put components (controller, 6 pylons, and chiseled quartz block) and right-click controller with wand, then they transformed into spire, and absorbed 3 types of essentias.
But spire did not provide any potentia to my harness, and had no lightning effects.

Please check it. Thanks

**Comment by Tuhljin** [comment]
Are you providing Aer vis by vis relay to the spire?

**Comment by esidav** [comment]
Ah, yes. I am providing.
Hm, I will re-check from scratch. Thanks.

**Comment by esidav** [comment]
I am confusing now...
In test world, created new, spire works well.
But in main world, it does not yet.
Some sort of data might be broken...?

Anyway, this is probably my own problem.
Thank you for responding. I will close this issue.
