### ISSUE TITLE
[1.8.9] Magic Hourglass randomly stops

### ISSUE THREAD

**Issue by Xiaminou** [Tuhljin/Automagy#45]
![2016-04-26_21 54 45](https://cloud.githubusercontent.com/assets/8670392/14832246/9d81bb06-0bf9-11e6-833d-4f5d02e1a9c1.png)
![2016-04-26_21 56 23](https://cloud.githubusercontent.com/assets/8670392/14832287/cdf6e2a2-0bf9-11e6-82d1-53e4609bc07b.png)

The Magic Hourglass in this setup randomly stops and does not restart. After a few minutes I have to flip a lever to restart it.

**Comment by Tuhljin** [comment]
Can the wiring above (or anything else around it besides the lever) output a redstone signal into the hourglass?

**Comment by Xiaminou** [comment]
Yes the Ender IO wiring most likely sends a signal to it, BUT even if it does it means it'd stop for the length of the pulse and then start again, which it does for a few minutes.
Yes, the bug is most likely caused by the wiring. But it is still a bug, and it shouldn't be happening.

**Comment by Tuhljin** [comment]
I'll look into it, but at least for now, I'd recommend placing your wiring so that it reads from one of the output-only sides of the hourglass.

**Comment by Xiaminou** [comment]
Oh wait, so I thought all sides were input-output. Right I suppose if I'd had put it on one of the side it would work.
