### ISSUE TITLE
[1.7.10] Essentia Locus & Essentia Aggregator not providing to mirrors.

### ISSUE THREAD

**Issue by cloakable** [Tuhljin/Automagy#57]
I have built an Essentia Locus on my server, and it currently reads my collection of jars correctly.

However, I installed an Essentia Aggregator beneath the lapis block, and it is not supplying the essentia it is reading to any mirrors. Putting the mirror near the jars works however.

https://imgur.com/a/OCmR7 screenshot of Essentia Locus setup.

Thaumcraft 4.2.3.5
Automagy 0.28.2

**Comment by kutschkem** [comment]
Can you specify what exactly you tried? In my world I have the problem that the Witching Gadgets Essentia Pump is not provided, but the infusion altar is.

**Comment by kutschkem** [comment]
Actually, I got it to work now. It seems that it works when the mirror is east or west from the locus, but not if it is north or south of it. Can you confirm that?

**Comment by cloakable** [comment]
Late return, but I found my problem: the aggregator goes between the lapis block and the locus (which isn't shown in the Thaumonomicon).
