### ISSUE TITLE
[Question] TC6 Someday

### ISSUE THREAD

**Issue by Alaberti** [Tuhljin/Automagy#68]
"Because someone has to be 'that guy'"

I know you're extremely busy, so that's why I'm leaving this an open issue - are there any plans to support Thaumcraft 6 on 1.12.2 "someday?"

**Comment by Tuhljin** [comment]
I hope so. That's the plan.

Not only am I busy, but I'm waiting for TC 6 to settle down a bit before diving into it. Some things require rethinking and I don't want to spend a lot of time doing something Azanor is going to cover well enough. (For instance, TC6 has an inventory system that makes the Inventarium, at least as it was previously, less of a necessity.)

**Comment by Aldermeer** [comment]
I'm still hoping for someone to replicate the Avarice/Miser's Pearl.
That was the very first thing I always strove for in TC4.
The magical boomerang is nice, but sooo sloooow compared.
